trying to
    cd fab_quickstart
    pyinstaller cli.py  # that fails, move to python setup...

better:
    
    source venv/bin/activate
    
    python setup.py install
        which initial laid an .egg??
    

    create build: https://packaging.python.org/tutorials/packaging-projects/
        
        deactivate  # fails if venv activate
        
        python3 -m pip install --user --upgrade setuptools wheel
        
        python3 setup.py sdist bdist_wheel
            produced expected dist/ output (yes!)
                FAB_Quickstart-0.9.0-py3-none-any.whl   (13kb)
                FAB-Quickstart-0.9.0.tar.gz             (12kb)

    now upload to testPi

        https://test.pypi.org/manage/account/#api-tokens

        deactivate

        python3 -m pip install --user --upgrade twine

        python3 -m twine upload --repository testpypi dist/*
            __token__
            << generated token >>

            View at https://test.pypi.org/project/FAB-Quickstart/0.9.0/
    
    to re-upload

        change version in fab_quickstart.__init__
        delete dist folder

        python3 -m pip install --user --upgrade twine

        see https://stackoverflow.com/questions/52016336/how-to-upload-new-versions-of-project-to-pypi-with-twine,
            so...

        python3 -m twine upload  --skip-existing --repository testpypi dist/*

        Worked: see https://test.pypi.org/project/FAB-Quickstart/0.9.1/

    now install it

        pip install -i https://test.pypi.org/simple/ FAB-Quickstart==0.9.0

            val@valMbp testPy % pip install -i https://test.pypi.org/simple/ FAB-Quickstart==0.9.0
            Looking in indexes: https://test.pypi.org/simple/
            Requirement already satisfied: FAB-Quickstart==0.9.0 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages/FAB_Quickstart-0.9.0-py3.8.egg (0.9.0)
            Requirement already satisfied: apispec[yaml]<4,>=3.3 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from FAB-Quickstart==0.9.0) (3.3.1)
            Requirement already satisfied: colorama<1,>=0.3.9 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from FAB-Quickstart==0.9.0) (0.4.3)
            Requirement already satisfied: click<8,>=6.7 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from FAB-Quickstart==0.9.0) (7.1.2)
            Requirement already satisfied: email_validator<2,>=1.0.5 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from FAB-Quickstart==0.9.0) (1.1.1)
            Requirement already satisfied: Flask<2,>=0.12 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from FAB-Quickstart==0.9.0) (1.1.2)
            Requirement already satisfied: Flask-Babel<2,>=1 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from FAB-Quickstart==0.9.0) (1.0.0)
            Requirement already satisfied: Flask-Login<0.5,>=0.3 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from FAB-Quickstart==0.9.0) (0.4.1)
            Requirement already satisfied: Flask-OpenID<2,>=1.2.5 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from FAB-Quickstart==0.9.0) (1.2.5)
            Requirement already satisfied: Flask-SQLAlchemy<3,>=2.4 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from FAB-Quickstart==0.9.0) (2.4.4)
            Requirement already satisfied: Flask-WTF<1,>=0.14.2 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from FAB-Quickstart==0.9.0) (0.14.3)
            Requirement already satisfied: Flask-JWT-Extended<4,>=3.18 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from FAB-Quickstart==0.9.0) (3.24.1)
            Requirement already satisfied: jsonschema<4,>=3.0.1 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from FAB-Quickstart==0.9.0) (3.2.0)
            Requirement already satisfied: marshmallow<4,>=3 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from FAB-Quickstart==0.9.0) (3.7.1)
            Requirement already satisfied: marshmallow-enum<2,>=1.5.1 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from FAB-Quickstart==0.9.0) (1.5.1)
            Requirement already satisfied: marshmallow-sqlalchemy<1,>=0.22.0 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from FAB-Quickstart==0.9.0) (0.23.1)
            Requirement already satisfied: python-dateutil<3,>=2.3 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from FAB-Quickstart==0.9.0) (2.8.1)
            Requirement already satisfied: prison<1.0.0,>=0.1.3 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from FAB-Quickstart==0.9.0) (0.1.3)
            Requirement already satisfied: PyJWT>=1.7.1 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from FAB-Quickstart==0.9.0) (1.7.1)
            Requirement already satisfied: sqlalchemy-utils<1,>=0.32.21 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from FAB-Quickstart==0.9.0) (0.36.8)
            Requirement already satisfied: PyYAML>=3.10; extra == "yaml" in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from apispec[yaml]<4,>=3.3->FAB-Quickstart==0.9.0) (5.3.1)
            Requirement already satisfied: dnspython>=1.15.0 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from email_validator<2,>=1.0.5->FAB-Quickstart==0.9.0) (2.0.0)
            Requirement already satisfied: idna>=2.0.0 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from email_validator<2,>=1.0.5->FAB-Quickstart==0.9.0) (2.10)
            Requirement already satisfied: Werkzeug>=0.15 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from Flask<2,>=0.12->FAB-Quickstart==0.9.0) (1.0.1)
            Requirement already satisfied: Jinja2>=2.10.1 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from Flask<2,>=0.12->FAB-Quickstart==0.9.0) (2.11.2)
            Requirement already satisfied: itsdangerous>=0.24 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from Flask<2,>=0.12->FAB-Quickstart==0.9.0) (1.1.0)
            Requirement already satisfied: pytz in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from Flask-Babel<2,>=1->FAB-Quickstart==0.9.0) (2020.1)
            Requirement already satisfied: Babel>=2.3 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from Flask-Babel<2,>=1->FAB-Quickstart==0.9.0) (2.8.0)
            Requirement already satisfied: python3-openid>=2.0 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from Flask-OpenID<2,>=1.2.5->FAB-Quickstart==0.9.0) (3.2.0)
            Requirement already satisfied: SQLAlchemy>=0.8.0 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from Flask-SQLAlchemy<3,>=2.4->FAB-Quickstart==0.9.0) (1.3.18)
            Requirement already satisfied: WTForms in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from Flask-WTF<1,>=0.14.2->FAB-Quickstart==0.9.0) (2.3.1)
            Requirement already satisfied: six in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from Flask-JWT-Extended<4,>=3.18->FAB-Quickstart==0.9.0) (1.15.0)
            Requirement already satisfied: setuptools in /Users/val/.local/lib/python3.8/site-packages (from jsonschema<4,>=3.0.1->FAB-Quickstart==0.9.0) (49.2.1)
            Requirement already satisfied: pyrsistent>=0.14.0 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from jsonschema<4,>=3.0.1->FAB-Quickstart==0.9.0) (0.16.0)
            Requirement already satisfied: attrs>=17.4.0 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from jsonschema<4,>=3.0.1->FAB-Quickstart==0.9.0) (19.3.0)
            Requirement already satisfied: MarkupSafe>=0.23 in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from Jinja2>=2.10.1->Flask<2,>=0.12->FAB-Quickstart==0.9.0) (1.1.1)
            Requirement already satisfied: defusedxml in /Users/val/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from python3-openid>=2.0->Flask-OpenID<2,>=1.2.5->FAB-Quickstart==0.9.0) (0.6.0)
            WARNING: You are using pip version 19.2.3, however version 20.2.1 is available.
            You should consider upgrading via the 'pip install --upgrade pip' command.
            val@valMbp testPy % FAB-quickstart
            zsh: command not found: FAB-quickstart
            val@valMbp testPy %


running Mac, Catalina



*****************************
PyInstaller fails as follows:
    OSError: Python library not found: libpython3.8.dylib, libpython3.8m.dylib, Python, .Python
        This would mean your Python installation doesn't come with proper library files.
        This usually happens by missing development package, or unsuitable build parameters of Python installation.

        * On Debian/Ubuntu, you would need to install Python development packages
        * apt-get install python3-dev
        * apt-get install python-dev
        * If you're building Python by yourself, please rebuild your Python with `--enable-shared` (or, `--enable-framework` on Darwin)


Research found these suggestions, all failed in same way

    python installed via pyenv install 3.8.3, at:
        /Users/val/.pyenv/versions/3.8.3/lib/python3.8

    per https://stackoverflow.com/questions/32578106/how-to-install-python-devel-in-mac-os
        brew reinstall python 
            val@valMbp ~ % brew reinstall python
                ==> Downloading https://homebrew.bintray.com/bottles/python%403.8-3.8.5.catalina.bottle.tar.gz
                Already downloaded: /Users/val/Library/Caches/Homebrew/downloads/9dd7cd94f1e3f75a7f2fe63c7333d9de7e8241f212eeaa1e774c45fff2da63f8--python@3.8-3.8.5.catalina.bottle.tar.gz
                ==> Reinstalling python@3.8 
                ==> Pouring python@3.8-3.8.5.catalina.bottle.tar.gz
                ==> /usr/local/Cellar/python@3.8/3.8.5/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/p
                ==> /usr/local/Cellar/python@3.8/3.8.5/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/p
                ==> /usr/local/Cellar/python@3.8/3.8.5/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/p
                ==> Caveats
                Python has been installed as
                /usr/local/bin/python3

                Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
                `python3`, `python3-config`, `pip3` etc., respectively, have been installed into
                /usr/local/opt/python@3.8/libexec/bin

                You can install Python packages with
                pip3 install <package>
                They will install into the site-package directory
                /usr/local/lib/python3.8/site-packages

                See: https://docs.brew.sh/Homebrew-and-Python
                ==> Summary
                🍺  /usr/local/Cellar/python@3.8/3.8.5: 4,331 files, 67MB
                Removing: /usr/local/Cellar/python/2.7.11... (5,052 files, 68.0MB)
                Removing: /Users/val/Library/Caches/Homebrew/python@3.8--3.8.3.tar.xz... (17MB)
                Removing: /Users/val/Library/Caches/Homebrew/python@3.8--setuptools--46.0.0.zip... (841.5KB)
                Removing: /Users/val/Library/Caches/Homebrew/python@3.8--pip--20.0.2.tar.gz... (1.4MB)
                Removing: /Users/val/Library/Caches/Homebrew/python@3.8--patch--c47680c85f201f5830bf71741f09ece031b99386040f3c70b20190b4c47fb81d.patch... (2KB)


    This page: https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html
    says set DYLD_LIBRARY_PATH  -- same result
        export DYLD_LIBRARY_PATH=/Users/val/.pyenv/versions/3.8.3/lib/python3.8
        or
        export DYLD_LIBRARY_PATH=/Users/val/.pyenv/versions/3.8.3-dev/lib/python3.8

    pyenv install 3.8-dev  -- same result

    https://stackoverflow.com/questions/43067039/pyinstaller-error-oserror-python-library-not-found-libpython3-4mu-so-1-0-lib
      libpython3.4m.so.1.0 --> /usr/lib -- but can't find mac version

    https://groups.google.com/forum/#!searchin/pyinstaller/pyinstaller$20OSError$3A$20Python$20library$20not$20found/pyinstaller/UJNSXQ6EI4M/KTVYFPVCAQAJ
      brew install pyqt  -- same result

Full Log:

    64 INFO: PyInstaller: 3.6
    64 INFO: Python: 3.8.3
    77 INFO: Platform: macOS-10.15.6-x86_64-i386-64bit
    78 INFO: wrote /Users/val/python/vscode/fab-quickstart/fab_quickstart/cli.spec
    83 INFO: UPX is not available.
    85 INFO: Extending PYTHONPATH with paths
    ['/Users/val/python/vscode/fab-quickstart',
    '/Users/val/python/vscode/fab-quickstart/fab_quickstart']
    85 INFO: checking Analysis
    85 INFO: Building Analysis because Analysis-00.toc is non existent
    85 INFO: Initializing module dependency graph...
    89 INFO: Caching module graph hooks...
    98 INFO: Analyzing base_library.zip ...
    2353 INFO: Processing pre-find module path hook   distutils
    2354 INFO: distutils: retargeting to non-venv dir '/Users/val/.pyenv/versions/3.8.3/lib/python3.8'
    5314 INFO: Caching module dependency graph...
    5441 INFO: running Analysis Analysis-00.toc
    5447 INFO: Analyzing /Users/val/python/vscode/fab-quickstart/fab_quickstart/cli.py
    5864 INFO: Processing module hooks...
    5864 INFO: Loading module hook "hook-pkg_resources.py"...
    6099 INFO: Processing pre-safe import module hook   win32com
    6322 INFO: Excluding import '__main__'
    6323 INFO:   Removing import of __main__ from module pkg_resources
    6324 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
    6324 INFO: Loading module hook "hook-lib2to3.py"...
    6329 INFO: Loading module hook "hook-encodings.py"...
    6407 INFO: Loading module hook "hook-sysconfig.py"...
    6420 INFO: Loading module hook "hook-xml.py"...
    6502 INFO: Loading module hook "hook-pydoc.py"...
    6502 INFO: Loading module hook "hook-distutils.py"...
    6533 INFO: Looking for ctypes DLLs
    6607 INFO: Analyzing run-time hooks ...
    6611 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
    6615 INFO: Including run-time hook 'pyi_rth_pkgres.py'
    6632 INFO: Looking for dynamic libraries
    6750 INFO: Looking for eggs
    6750 INFO: Python library not in binary dependencies. Doing additional searching...
    Traceback (most recent call last):
    File "/Users/val/python/vscode/fab-quickstart/venv/bin/pyinstaller", line 8, in <module>
        sys.exit(run())
    File "/Users/val/python/vscode/fab-quickstart/venv/lib/python3.8/site-packages/PyInstaller/__main__.py", line 114, in run
        run_build(pyi_config, spec_file, **vars(args))
    File "/Users/val/python/vscode/fab-quickstart/venv/lib/python3.8/site-packages/PyInstaller/__main__.py", line 65, in run_build
        PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
    File "/Users/val/python/vscode/fab-quickstart/venv/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 734, in main
        build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
    File "/Users/val/python/vscode/fab-quickstart/venv/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 681, in build
        exec(code, spec_namespace)
    File "/Users/val/python/vscode/fab-quickstart/fab_quickstart/cli.spec", line 6, in <module>
        a = Analysis(['cli.py'],
    File "/Users/val/python/vscode/fab-quickstart/venv/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 244, in __init__
        self.__postinit__()
    File "/Users/val/python/vscode/fab-quickstart/venv/lib/python3.8/site-packages/PyInstaller/building/datastruct.py", line 160, in __postinit__
        self.assemble()
    File "/Users/val/python/vscode/fab-quickstart/venv/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 478, in assemble
        self._check_python_library(self.binaries)
    File "/Users/val/python/vscode/fab-quickstart/venv/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 568, in _check_python_library
        python_lib = bindepend.get_python_library_path()
    File "/Users/val/python/vscode/fab-quickstart/venv/lib/python3.8/site-packages/PyInstaller/depend/bindepend.py", line 945, in get_python_library_path
        raise IOError(msg)
    OSError: Python library not found: libpython3.8m.dylib, .Python, Python, libpython3.8.dylib
        This would mean your Python installation doesn't come with proper library files.
        This usually happens by missing development package, or unsuitable build parameters of Python installation.

        * On Debian/Ubuntu, you would need to install Python development packages
        * apt-get install python3-dev
        * apt-get install python-dev
        * If you're building Python by yourself, please rebuild your Python with `--enable-shared` (or, `--enable-framework` on Darwin)
